"""Schema package placeholder."""
from app.schemas.auth import AuthResponse, CurrentUserResponse, LoginRequest, RegisterRequest
from app.schemas.candidate_profile import (
    CandidateDashboardSummary,
    CandidateProfileCreate,
    CandidateProfileResponse,
    CandidateProfileUpdate,
)
from app.schemas.document import (
    ChunkResponse,
    DocumentChunkingResponse,
    DocumentIndexingResponse,
    DocumentResponse,
)
from app.schemas.generation import (
    CandidateAnswerGuidanceResponse,
    CandidateGenerationRequest,
    CandidateInterviewQuestionResponse,
    CandidateInterviewQuestionsResponse,
    CandidateSkillGapAnalysisResponse,
    CandidateSkillGapItemResponse,
    CandidateStarAnswerResponse,
    CandidateStarSectionResponse,
    CandidateStrengthSignalResponse,
    GenerationQueryRequest,
    GenerationResponse,
    GroundedPromptType,
    RecruiterConcernResponse,
    RecruiterFitSummaryResponse,
    RecruiterGenerationRequest,
    RecruiterInterviewPackResponse,
    RecruiterInterviewProbeResponse,
    RecruiterStrengthSignalResponse,
    SkillGapSeverity,
)
from app.schemas.recruiter import (
    RecruiterCandidateIntakeCreate,
    RecruiterCandidateResponse,
    RecruiterJobCreate,
    RecruiterJobDetailResponse,
    RecruiterJobListItemResponse,
    RecruiterJobListResponse,
)
from app.schemas.report import (
    SavedReportCreateRequest,
    SavedReportHistoryResponse,
    SavedReportListItemResponse,
    SavedReportResponse,
)
from app.schemas.retrieval import EvidenceChunkResponse, RetrievalQueryRequest, RetrievalResponse

__all__ = [
    "AuthResponse",
    "CandidateAnswerGuidanceResponse",
    "CandidateGenerationRequest",
    "CandidateDashboardSummary",
    "CandidateInterviewQuestionResponse",
    "CandidateInterviewQuestionsResponse",
    "CandidateSkillGapAnalysisResponse",
    "CandidateSkillGapItemResponse",
    "CandidateProfileCreate",
    "CandidateProfileResponse",
    "CandidateProfileUpdate",
    "CandidateStarAnswerResponse",
    "CandidateStarSectionResponse",
    "CandidateStrengthSignalResponse",
    "ChunkResponse",
    "CurrentUserResponse",
    "DocumentChunkingResponse",
    "DocumentIndexingResponse",
    "DocumentResponse",
    "EvidenceChunkResponse",
    "GenerationQueryRequest",
    "GenerationResponse",
    "GroundedPromptType",
    "LoginRequest",
    "RecruiterConcernResponse",
    "RecruiterCandidateIntakeCreate",
    "RecruiterCandidateResponse",
    "RecruiterFitSummaryResponse",
    "RecruiterGenerationRequest",
    "RecruiterInterviewPackResponse",
    "RecruiterInterviewProbeResponse",
    "RecruiterJobCreate",
    "RecruiterJobDetailResponse",
    "RecruiterJobListItemResponse",
    "RecruiterJobListResponse",
    "RecruiterStrengthSignalResponse",
    "RetrievalQueryRequest",
    "RetrievalResponse",
    "RegisterRequest",
    "SavedReportCreateRequest",
    "SavedReportHistoryResponse",
    "SavedReportListItemResponse",
    "SavedReportResponse",
    "SkillGapSeverity",
]
